version: '1.0'

services:
  php-fpm:
    image: php:8.1-fpm
    container_name: php-fpm
    volumes:
      - ./:/var/www/
    working_dir: /var/www

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./api/:/var/www/api/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm

